// Get active survey
export const GET_ACTIVE_SURVEY_IN_PROGRESS = 'GET_ACTIVE_SURVEY_IN_PROGRESS';
export const GET_ACTIVE_SURVEY_SUCCESS = 'GET_ACTIVE_SURVEY_SUCCESS';
export const GET_ACTIVE_SURVEY_FAILURE = 'GET_ACTIVE_SURVEY_FAILURE';

// Get single survey
export const GET_SURVEY_IN_PROGRESS = 'GET_SURVEY_IN_PROGRESS';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_FAILURE = 'GET_SURVEY_FAILURE';

// Answer question
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const MARK_SURVEY_AS_DONE = 'MARK_SURVEY_AS_DONE';

// Submit survey
export const SUBMIT_SURVEY_IN_PROGRESS = 'SUBMIT_SURVEY_IN_PROGRESS';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';
